#!/usr/bin/env python3
"""Generates compiler/src/gd_props.rs: which kind of value each (object id, property key) holds.

Source of truth is the community GD 2.2 property schema (gd-info-explorer schema.txt).
"""
import collections
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import schema as S

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "compiler", "src", "gd_props.rs")

types, classes, ids = S.parse()


def kind_for(type_name: str) -> str:
    t = type_name
    if t in ("GroupID", "GroupOrControlID", "GroupOrEffectID", "ColorOrGroupID"):
        return "Group"
    if t == "ColorID":
        return "Color"
    if t in ("ItemID", "TimerID", "ItemOrTimerID"):
        return "Item"
    if t == "BlockID":
        return "Block"
    if t in ("GroupList", "RemapList"):
        return "GroupList"
    if t in ("AdvRandomList", "SequenceList"):
        return "GroupPairs"
    if t == "Bool":
        return "Bool"
    if t in ("String", "HSVString", "ParticleString", "EventList"):
        return "Text"
    return "Number"


# (obj id, key) -> kind
per_obj = {}
for oid, cname in ids.items():
    if cname not in classes:
        continue
    for name, key, typ, _ in S.all_props(classes, cname):
        k = kind_for(typ)
        # `single_group` (33) is declared Int in the schema but is a group id
        if key == 33:
            k = "Group"
        # `color_1` / `color_2` (21, 22) are declared Int but are color channel ids
        if key in (21, 22):
            k = "Color"
        per_obj[(oid, key)] = k

# universal kind per key = plurality across object ids
by_key = collections.defaultdict(collections.Counter)
for (oid, key), k in per_obj.items():
    by_key[key][k] += 1
universal = {key: c.most_common(1)[0][0] for key, c in by_key.items()}
universal[33] = "Group"
universal[21] = universal[22] = "Color"

exceptions = sorted((oid, key, k) for (oid, key), k in per_obj.items() if universal[key] != k)

lines = []
w = lines.append
w("// @generated by spwn-tools/gen_props_rs.py from the community GD 2.2 object property schema.")
w("// Do not edit by hand; regenerate instead.")
w("//")
w("// Describes what kind of value every (object id, property key) pair holds, so level strings can")
w("// be read (and their group/color/block/item ids reserved) correctly for 2.2 objects.")
w("")
w("#[derive(Debug, Clone, Copy, PartialEq, Eq)]")
w("pub enum Kind {")
w("    Group,")
w("    Color,")
w("    Block,")
w("    Item,")
w("    /// period separated list of group ids (`1.2.3`)")
w("    GroupList,")
w("    /// period separated list of (group id, number) pairs (`1.50.2.30`)")
w("    GroupPairs,")
w("    Bool,")
w("    Text,")
w("    Number,")
w("}")
w("")
w("/// The kind of value stored under `key` for the object with id `obj_id`.")
w("/// Mixed-type properties (like the pulse trigger's target) need extra context,")
w("/// see `pulse_target_is_group` in the callers.")
w("pub fn kind_of(obj_id: u16, key: u16) -> Kind {")
w("    use Kind::*;")
w("    match (obj_id, key) {")
for oid, key, k in exceptions:
    w(f"        ({oid}, {key}) => {k},")
w("        _ => universal(key),")
w("    }")
w("}")
w("")
w("fn universal(key: u16) -> Kind {")
w("    use Kind::*;")
w("    match key {")
groups = collections.defaultdict(list)
for key, k in sorted(universal.items()):
    groups[k].append(key)
for k, keys in groups.items():
    if k == "Number":
        continue
    w("        " + " | ".join(str(x) for x in keys) + f" => {k},")
w("        _ => Number,")
w("    }")
w("}")
w("")
open(OUT, "w").write("\n".join(lines))
print("wrote", OUT, "-", len(exceptions), "exceptions,", len(universal), "universal keys")
