// @generated by spwn-tools/gen_props_rs.py from the community GD 2.2 object property schema.
// Do not edit by hand; regenerate instead.
//
// Describes what kind of value every (object id, property key) pair holds, so level strings can
// be read (and their group/color/block/item ids reserved) correctly for 2.2 objects.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Kind {
    Group,
    Color,
    Block,
    Item,
    /// period separated list of group ids (`1.2.3`)
    GroupList,
    /// period separated list of (group id, number) pairs (`1.50.2.30`)
    GroupPairs,
    Bool,
    Text,
    Number,
}

/// The kind of value stored under `key` for the object with id `obj_id`.
/// Mixed-type properties (like the pulse trigger's target) need extra context,
/// see `pulse_target_is_group` in the callers.
pub fn kind_of(obj_id: u16, key: u16) -> Kind {
    use Kind::*;
    match (obj_id, key) {
        (1815, 80) => Block,
        (1815, 95) => Block,
        (1816, 80) => Block,
        (2913, 71) => Color,
        (2914, 71) => Number,
        (2915, 71) => Number,
        (2919, 51) => Color,
        (3024, 51) => Number,
        (3033, 76) => Group,
        (3609, 80) => Block,
        (3609, 95) => Block,
        (3619, 51) => Item,
        _ => universal(key),
    }
}

fn universal(key: u16) -> Kind {
    use Kind::*;
    match key {
        4 | 5 | 11 | 13 | 15 | 16 | 17 | 34 | 36 | 41 | 42 | 48 | 52 | 55 | 56 | 58 | 59 | 60 | 62 | 64 | 65 | 66 | 67 | 70 | 78 | 81 | 86 | 87 | 89 | 93 | 94 | 96 | 98 | 99 | 100 | 102 | 103 | 104 | 106 | 110 | 111 | 112 | 116 | 117 | 121 | 122 | 123 | 126 | 127 | 133 | 134 | 135 | 136 | 137 | 138 | 139 | 141 | 142 | 146 | 147 | 153 | 154 | 157 | 169 | 171 | 172 | 184 | 185 | 186 | 187 | 188 | 190 | 192 | 193 | 194 | 200 | 201 | 207 | 208 | 210 | 211 | 212 | 214 | 241 | 255 | 261 | 276 | 278 | 279 | 280 | 281 | 283 | 284 | 287 | 289 | 305 | 306 | 307 | 336 | 337 | 338 | 339 | 345 | 347 | 351 | 352 | 353 | 356 | 368 | 369 | 370 | 372 | 375 | 376 | 377 | 378 | 380 | 381 | 382 | 387 | 388 | 389 | 393 | 394 | 397 | 399 | 400 | 407 | 412 | 413 | 414 | 415 | 417 | 418 | 419 | 420 | 428 | 433 | 439 | 441 | 443 | 444 | 445 | 452 | 453 | 459 | 460 | 461 | 463 | 464 | 465 | 466 | 468 | 469 | 471 | 472 | 474 | 475 | 487 | 489 | 491 | 492 | 493 | 494 | 495 | 496 | 500 | 503 | 504 | 505 | 507 | 508 | 509 | 510 | 511 | 513 | 514 | 515 | 528 | 529 | 531 | 535 | 539 | 540 | 541 | 542 | 543 | 544 | 551 | 570 | 571 | 577 | 581 | 584 | 585 | 587 | 589 | 591 | 592 | 595 | 599 => Bool,
        21 | 22 | 23 | 50 | 260 => Color,
        31 | 43 | 44 | 49 | 145 | 430 => Text,
        33 | 51 | 71 | 395 | 448 | 457 | 516 | 517 | 518 | 519 => Group,
        57 | 274 | 442 => GroupList,
        80 | 95 => Item,
        152 | 435 => GroupPairs,
        _ => Number,
    }
}
